
    create table genre (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table movie (
       id bigint generated by default as identity,
        imdb_key varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table movie_genre_list (
       movie_id bigint not null,
        genre_list_id bigint not null
    );

    create table movie_player_list (
       movie_id bigint not null,
        player_list_id bigint not null
    );

    create table player (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    alter table movie_genre_list
       add constraint FKcxhh67b6irn3yb7o32ny8em1b
       foreign key (genre_list_id)
       references genre;

    alter table movie_genre_list
       add constraint FKatvkfhllpifbwi71s1xvm2q8p
       foreign key (movie_id)
       references movie;

    alter table movie_player_list
       add constraint FK3naocl7dy0y3ywvwvp4il8lu7
       foreign key (player_list_id)
       references player;

    alter table movie_player_list
       add constraint FKpela2fs7b4sny52a7du490tle
       foreign key (movie_id)
       references movie;